# Generated by Django 4.1.4 on 2023-07-17 10:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CusUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metaMask", models.CharField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("avatar", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=200)),
                ("phoneNumber", models.CharField(max_length=200)),
                ("DOB", models.DateField()),
                ("address", models.JSONField(default=api.models.CusUser.corDefault)),
                (
                    "subscription",
                    models.JSONField(default=api.models.CusUser.subDefault),
                ),
            ],
        ),
    ]
