# Generated by Django 4.1.4 on 2023-07-17 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_alter_cususer_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="cususer",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cususer",
            name="metaMask",
            field=models.CharField(max_length=200),
        ),
    ]
