# Generated by Django 4.1.4 on 2023-07-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_cususer_user_alter_cususer_metamask"),
    ]

    operations = [
        migrations.RemoveField(model_name="cususer", name="password",),
    ]
