# Generated by Django 4.1.4 on 2023-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_cususer_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cususer",
            name="DOB",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cususer",
            name="avatar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="cususer",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="cususer",
            name="firstName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cususer",
            name="gender",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="cususer",
            name="lastName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cususer",
            name="metaMask",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="cususer",
            name="phoneNumber",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="cususer",
            name="username",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
